In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
#存储数据集的目录
filePath = '../../data/CICDS2019/'
files=os.listdir(filePath)

In [3]:
files

['cicddos2019_dataset.csv']

In [6]:
#读取IDS2019数据集
df=pd.read_csv('../../data/CICDS2019/Benign_Many_vs_Many.csv')

In [7]:
df

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound,Label
0,6,110861755,26,26,616.0,768.0,297.0,0.0,23.692308,80.460062,...,198805.454545,64223.338986,392446.0,179351.0,9.863210e+06,413171.813769,10007500.0,8632089.0,0,BENIGN
1,6,40335006,9,10,8.0,62.0,1.0,0.0,0.888889,0.333333,...,90226.500000,43.554563,90287.0,90185.0,9.993447e+06,40495.753715,10018634.0,9933709.0,0,BENIGN
2,0,113244633,56,0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,248176.750000,859690.585416,2978061.0,4.0,9.188876e+06,809901.667647,9882838.0,6781893.0,0,BENIGN
3,6,95628949,21,20,20.0,0.0,1.0,0.0,0.952381,0.218218,...,14901.222222,177.422362,15367.0,14798.0,1.001418e+07,5184.077926,10016037.0,10000366.0,0,BENIGN
4,6,95613243,21,20,20.0,0.0,1.0,0.0,0.952381,0.218218,...,26508.333333,17.902514,26534.0,26473.0,1.000431e+07,21.430119,10004365.0,10004289.0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465498,17,2,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.0,1,Portmap
1465499,17,1,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.0,1,Portmap
1465500,17,1,2,0,422.0,0.0,211.0,211.0,211.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.0,1,Portmap
1465501,17,1,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.0,1,Portmap
1465502,17,1,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.0,1,Portmap

In [8]:
# 判断是否存在空值
df.isna().any()[df.isna().any()]

Series([], dtype: bool)

In [9]:
# 判断是否存在inf值
for column in list(df.columns)[:-1]:
    if np.isinf(df[column]).any():
        print (column)

In [10]:
df.shape

(1465503, 70)

In [11]:
# 处理Label
Label = df['Label']

In [12]:
list(pd.value_counts(Label).keys())

['BENIGN',
 'DNS',
 'LDAP',
 'MSSQL',
 'NetBIOS',
 'NTP',
 'SNMP',
 'SSDP',
 'UDP',
 'Syn',
 'TFTP',
 'UDPLag',
 'Portmap']

In [13]:
# 使用sklearn之LabelEncoder将Label标准化
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Label)

LabelEncoder()

In [14]:
# 进行转化
label_bin=le.transform(Label)
# 显示标签转换后的结果
list(pd.value_counts(label_bin).keys())

[0, 1, 2, 3, 5, 4, 7, 8, 11, 9, 10, 12, 6]

In [16]:
# 显示数字所对应的标签
print(le.inverse_transform([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]))

['BENIGN' 'DNS' 'LDAP' 'MSSQL' 'NTP' 'NetBIOS' 'Portmap' 'SNMP' 'SSDP'
 'Syn' 'TFTP' 'UDP' 'UDPLag']

In [17]:
# 保存前需要Reshape
label_bin = label_bin.reshape(label_bin.shape[0],1)
label_bin.shape

(1465503, 1)

In [18]:
subdf = pd.DataFrame()
for label in list(pd.value_counts(Label).keys()):
    df_temp = df[df['Label'] == label]
    if(df['Label'][df['Label']==label].count()>10293):
        df_temp = df_temp.sample(frac=0.01)
    elif(df['Label'][df['Label']==label].count()<1507):
        df_temp = df_temp.sample(frac=1)
    else:
        df_temp = df_temp.sample(frac=0.1)
    df_temp.reset_index(drop=True, inplace=True)
    # df_temp[" Label"].value_counts()
    subdf = pd.concat([df_temp,subdf])
    subdf.reset_index(drop=True, inplace=True)
subdf["Label"].value_counts()

Label
Portmap    1127
UDPLag     1127
TFTP       1127
Syn        1127
UDP        1127
SSDP       1127
SNMP       1127
NTP        1127
NetBIOS    1127
MSSQL      1127
LDAP       1127
DNS        1127
BENIGN     1127
Name: count, dtype: int64

In [19]:
subdf

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound,Label
0,17,1,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,Portmap
1,17,1,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,Portmap
2,17,1,2,0,422.0,0.0,211.0,211.0,211.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,Portmap
3,17,1,2,0,422.0,0.0,211.0,211.0,211.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,Portmap
4,17,1,2,0,458.0,0.0,229.0,229.0,229.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,Portmap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14646,6,15151,1,1,6.0,6.0,6.0,6.0,6.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,BENIGN
14647,17,21297,2,2,74.0,186.0,37.0,37.0,37.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,BENIGN
14648,6,7299753,2,8,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,BENIGN
14649,6,40904,1,1,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,BENIGN
14650,6,10243769,29,30,4552.0,30182.0,1130.0,0.0,156.965517,330.047668,...,288702.0,0.0,288702.0,288702.0,9954904.0,0.0,9954904.0,9954904.0,0,BENIGN

In [20]:
# 归一化处理 可选
from sklearn.preprocessing import  StandardScaler

standard_scaler_df=StandardScaler().fit_transform(subdf.iloc[:,:-1])
np.save('../../data/CICDS2019/sub/sub_X.npy',standard_scaler_df)

In [21]:
Label = subdf['Label']
# 使用sklearn之LabelEncoder将Label标准化
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Label)

LabelEncoder()

In [22]:
# 进行转化
label_le=le.transform(Label)
label_le = label_le.reshape(label_le.shape[0],1)
label_le.shape

(14651, 1)

In [23]:
np.save('../../data/CICDS2019/sub/sub_Y.npy',label_le)